---
tune_hugepages: 1024
tune_swappiness: 10
tune_max_map_count: 655360
tune_dirty_ratio: 40
tune_dirty_background_ratio: 10
tune_core_pattern: "/mnt/disk1/corefiles/core-%e-%p-%t"
tune_thp_mode: madvise
tune_cpupower_idle_disable: 3

tune_tcp_window_scaling: 1
tune_tcp_timestamps: 1
tune_tcp_mem: "761187 1014916 1522374"
tune_tcp_wmem: "4096 16777216 16777216"
tune_tcp_rmem: "4096 16777216 16777216"
tune_rmem_max: 16777216
tune_wmem_max: 16777216
